<?php
/*
Plugin Name: VN carlendar
Plugin URI: http://www.theanh.vui360.com/blog/2009/02/07/vn-calendar/
Description: Calendar for Vietnamese
Version: 1.0
Author: As247
Author URI: http://as247.vui360.com
  
Copyright 2009  As247  (email : as_3345@yahoo.com)

Especially thanks to Ho Ngoc Duc (http://www.informatik.uni-leipzig.de/~duc/) for javascript lunar calendar



*/
if (!defined('WP_CONTENT_DIR')) {
	define( 'WP_CONTENT_DIR', ABSPATH.'wp-content');
}
if (!defined('WP_CONTENT_URL')) {
	define('WP_CONTENT_URL', get_option('siteurl').'/wp-content');
}
if (!defined('WP_PLUGIN_DIR')) {
	define('WP_PLUGIN_DIR', WP_CONTENT_DIR.'/plugins');
}
if (!defined('WP_PLUGIN_URL')) {
	define('WP_PLUGIN_URL', WP_CONTENT_URL.'/plugins');
}
if(!function_exists(is_checked)){
	function is_checked($show_or_not) {
		if ($show_or_not == 1) return 'checked';
		else return '';
	}
}
function as_cal_js() {
	$woptions = get_option('as_vncal_widget');
	$caloptions= get_option('as_vncal');
	echo "\n".'<!-- Generated By VN Carlendar - http://www.theanh.vui360.com/ -->'."\n";
	echo '<script src="'.WP_PLUGIN_URL.'/vn-calendar/vncal.js.php?w='.$woptions['width'].'&fs='.$woptions['font_size'].'&cs='.$caloptions['use_custom_style'].'&ts='.$caloptions['timestamp'].'" type="text/javascript"></script>'."\n";
}
add_action('wp_head', 'as_cal_js');
function as_cal_widget() {	
	
	if ( !function_exists('register_sidebar_widget') || !function_exists('register_widget_control') )
		return;

	function widget_cal($args) {
		extract($args);
		$options = get_option('as_vncal_widget');
		$title =$options['title'];
		echo $before_widget.$before_title.$title.$after_title;
		echo '<ul><li><div id="AsCalendar"></div></li></ul><script>printSelectedMonth();</script>';
		if($options['showtime']) {
		echo '<ul><li><div id="AsTimeDiv"></div></li></ul><script>showVietCal();</script>';
		}
		echo $after_widget;
	}
		
	
	function as_cal_widget_control() {
		$default_options=array();
		$default_options['title']="VN calendar";
		$default_options['width']=192;
		$default_options['font_size']=9;
		$default_options['showtime']=0;
	
		$options = get_option('as_vncal_widget');
		if (!is_array($options)){
			$options=$default_options;
			//update_option('as_vncal_widget', $default_options);
		}
			
		if ($_POST['as_vncal-submit']) {
			$options['title'] = strip_tags($_POST['as_vncal-title']);
			$options['width'] = intval($_POST['as_vncal-width']);
			$options['font_size'] = intval($_POST['as_vncal-font_size']);
			$options['showtime'] = ($_POST['as_vncal-showtime'] == 1) ? 1 : 0;
			update_option('as_vncal_widget', $options);
		}
		echo '<p style="text-align: left;"><label for="as_vncal-title">';
		_e('Title', 'as-vncalendar');
		echo ': </label><input type="text" id="as_vncal-title" name="as_vncal-title" value="'.htmlspecialchars(stripslashes($options['title'])).'" /></p>'."\n";
		
		echo '<p style="text-align: left;"><label for="as_vncal-width">';
		_e('width', 'as-vncalendar');
		echo ': </label><input type="text" id="as_vncal-width" name="as_vncal-width" value="'.intval($options['width']).'" size="3" /></p>'."\n";
		
		echo '<p style="text-align: left;"><label for="as_vncal-font_size">';
		_e('Font size', 'as-vncalendar');
		echo ': </label><input type="text" id="as_vncal-font_size" name="as_vncal-font_size" value="'.intval($options['font_size']).'" size="3" /></p>'."\n";
		
		echo '<p style="text-align: left;"><label for="as_vncal-showtime">';
		_e('Showtime', 'as-vncalendar');
		echo ': </label><input type="checkbox" name="as_vncal-showtime" id="as_vncal-showtime" value="1" '.is_checked($options['showtime'])."/></p>"."\n";
		
		echo '<input type="hidden" id="as_vncal-submit" name="as_vncal-submit" value="1" />'."\n";
	}
	register_sidebar_widget(__('VN Calendar','as-vncalendar'), 'widget_cal');
	register_widget_control(array('VN Calendar', 'as-vncalendar'), 'as_cal_widget_control');
}
add_action('plugins_loaded', 'as_cal_widget');

function vncal_init(){
	
	$as_vncal_options = array();
	$as_vncal_options['use_custom_style']=0;
	$as_vncal_options['timestamp']=7*60*60;
	$as_vncal_options['custom_style']='<style type="text/css">
		.tennam {text-align:center; font-size:150%; line-height:120%; font-weight:bold; color:#000000; background-color: #CCCCCC}
	   .thang {font-size: 9; padding:1; line-height:100%; font-family:Tahoma,Verdana,Arial; table-layout:fixed}
	   .tenthang {text-align:center; font-size:125%; line-height:100%; font-weight:bold; color:#330033; background-color: #CCFFCC}
	  .navi-l {text-align:center; font-size:75%; line-height:100%; font-family:Verdana,Times New Roman,Arial; font-weight:bold; color:red; background-color: #CCFFCC}
	   .navi-r {text-align:center; font-size:75%; line-height:100%; font-family:Verdana,Arial,Times New Roman; font-weight:bold; color:#330033; background-color: #CCFFCC}
	   .ngaytuan {width:14%; text-align:center; font-size:125%; line-height:100%; color:#330033; background-color: #FFFFCC}
	   .ngaythang {background-color:#FDFDF0}
	   .homnay {background-color:#FFF000}
	   .tet {background-color:#FFCC99}
	   .am {text-align:right;font-size:75%;line-height:100%;color:blue}
	   .am2 {text-align:right;font-size:75%;line-height:100%;color:#004080}
	   .t2t6 {text-align:left;font-size:125%;color:black}
	   .t7 {text-align:left;font-size:125%;line-height:100%;color:green}
	   .cn {text-align:left;font-size:125%;line-height:100%;color:red}
	 -->
	 </style>';
	 add_option('as_vncal', $as_vncal_options, 'VN Calendar Options');
}
add_action('activate_vn-calendar/vncalendar.php', 'vncal_init');
function as_add_cal_opt_page()
{
	add_options_page('Calendar Options', 'VN Calendar Options',8, basename(__FILE__), as_cal_opt_page);
}
add_action('admin_menu', 'as_add_cal_opt_page');
function as_cal_css(){
	$options=get_option('as_vncal');
	if($options['use_custom_style']){
	echo "\n".'<!-- Generated By VN calendar -->'."\n";
	echo stripslashes($options['custom_style'])."\n";
	}
}
add_action('wp_head', 'as_cal_css');
function as_cal_opt_page()
{
	date_default_timezone_set('UTC');
	if($_POST['vncal_option-submit']){
		$opt=get_option('as_vncal');
		$current_time=mktime($_POST['gio'],$_POST['phut'],$_POST['giay'],$_POST['thang'],$_POST['ngay'],$_POST['nam']);
		if($_POST['gmt7']==1)
			$timestamp=7*60*60;
		else if($_POST['vncal_verify']==1)
			$timestamp=$current_time-time();
		else $timestamp=$opt['timestamp'];
		$options['timestamp']=$timestamp;
		$options['use_custom_style'] = ($_POST['use_custom_style'] == 1) ? 1 : 0;
		$options['custom_style']=trim($_POST['custom_style']);
		update_option('as_vncal', $options);
	}
	$options=get_option('as_vncal');
	//echo "a".$options['use_custom_style'];
	$width=$_GET['w'];
	$fontsize=$_GET['fs'];
	$customstyle=$_GET['cs'];
	$timestamp=$options['timestamp'];
	//echo $timestamp;
	$alltime=time()+$timestamp;
	$alltime = date('H|i|s|d|m|Y',$alltime);
	$alltime=explode('|',$alltime);
	$time['gio']=$alltime[0];
	$time['phut']=$alltime[1];
	$time['giay']=$alltime[2];
	$time['ngay']=$alltime[3];
	$time['thang']=$alltime[4];
	$time['nam']=$alltime[5];

	?>
<h1> VN CALENDAR OPTIONS</h1><br/>
	

	<form method="post" action="">
	<p><strong>Change time:</strong></p>
	<p><label for="gmt7">GMT+7<small>(this option change time to GMT+7)</small></label>
	<input type="checkbox" name="gmt7" id="gmt7" value="1" ></p> 
	<p><label for="vncal_verify">Verify<small>(please check this box if you want to change time)</small></label>
	<input type="checkbox" name="vncal_verify" id="vncal_verify" value="1" ><br/>
	<input type="text" name="gio" value="<?php echo $time['gio'];?>" size="1"/>h&nbsp;
	<input type="text" name="phut" value="<?php echo $time['phut'];?>" size="1"/>m&nbsp;
	<input type="text" name="giay" value="<?php echo $time['giay'];?>" size="1"/>s&nbsp;
	<input type="text" name="ngay" value="<?php echo $time['ngay'];?>" size="1"/>D&nbsp;
	<input type="text" name="thang" value="<?php echo $time['thang'];?>" size="1"/>M&nbsp;
	<input type="text" name="nam" value="<?php echo $time['nam'];?>" size="2"/>Y&nbsp;<br/><br/>
	</p> 
	<p><strong>Custom style</strong></p>
	<p><label for="use_custom_style">Use custom style?</label>
	<input type="checkbox" name="use_custom_style" id="use_custom_style" value="1" <?php echo is_checked($options['use_custom_style'])?>></p> 
	<br/>
	<textarea rows="7" name="custom_style" cols="100"><?php echo htmlspecialchars(stripslashes($options['custom_style']))?></textarea>
	<input type="hidden" name="vncal_option-submit" value="1" />
	<br/>
	<p class="submit">
	<input type="submit"  value="Update options" />
	</p>
	</form>
	<?php
}
?>